{% set version = "1.4.7" %}

{% set posix = 'm2-' if win else '' %}

package:
  name: r-httr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/httr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/httr/httr_{{ version }}.tar.gz
  sha256: 1555e6c2fb67bd38ff11b479f74aa287b2d93f4add487aec53b836ff07de3a3a

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:

  host:
    - r-base
    - r-r6
    - r-curl >=0.9.1
    - r-jsonlite
    - r-mime
    - r-openssl >=0.8

  run:
    - r-base
    - r-r6
    - r-curl >=0.9.1
    - r-jsonlite
    - r-mime
    - r-openssl >=0.8

test:
  commands:
    - $R -e "library('httr')"           # [not win]
    - "\"%R%\" -e \"library('httr')\""  # [win]

about:
  home: https://github.com/r-lib/httr
  license: MIT
  summary: Useful tools for working with HTTP organised by HTTP verbs (GET(), POST(), etc). Configuration functions make it easy to control additional request components (authenticate(), add_headers() and so on).
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
