{% set version = '1.4.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-httr
  version: {{ version|replace("-", "_") }}

source:
  fn: httr_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/httr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/httr/httr_{{ version }}.tar.gz
  sha256: d633f1425da514f65f3b8c034ae0a8b6911995009840c6bb9657ceedb99ddb48

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 1000

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:

  host:
    - r-base
    - r-r6
    - r-curl >=0.9.1
    - r-jsonlite
    - r-mime
    - r-openssl >=0.8

  run:
    - r-base
    - r-r6
    - r-curl >=0.9.1
    - r-jsonlite
    - r-mime
    - r-openssl >=0.8

test:
  commands:
    - $R -e "library('httr')"           # [not win]
    - "\"%R%\" -e \"library('httr')\""  # [win]

about:
  home: https://github.com/r-lib/httr
  license: MIT
  summary: Useful tools for working with HTTP organised by HTTP verbs (GET(), POST(), etc). Configuration
    functions make it easy to control additional request components (authenticate(),
    add_headers() and so on).
  license_family: MIT
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\MIT'  # [win]

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
