travis:
  secure:
    BINSTAR_TOKEN: jRZ0ObUFG5p1wV4dujxZQvCclmb6uWzo+5qdD5V/Jc1kIlRDtIoQk70th4ihY5XSpLRPy2Nr9e2gTfBhqxOMp1Vjx3q1N6iaQfDwOZcR0oY6fONM2mhu/V9xg7cAR7f+QTLk7D6tUBHO0YxklmJcoJwLSrv6duQ1DKNEeUemxFsQkF1UzFtSXUGOAtIfucOBtvmyvtTy48THn06CsG7nvFmddsf0aps27cORMw7CaXMQdzG9iiQlBm6AYfKOBmUlthx+U1xZJnP0gtiYm+cc1kN0CazRajpQSrPqMPJU1zRmS438vuEU3hhz8EhU8dO5YmL0t5aqWlzoiWZZ1/52+aba3BjFdIQvjFyXKFNqOJeWqPY2SFWOV6Sa7h3BdJvd9rnTyxnDlrMNqhPrp3naZZTm0dtRj3tk34XVo7PwTNmHuqprQXHxJ8e9jUGKf1STErQw7yP6R7/iDv62hZYMiMLTQxu2OKiTk8x0n8QeTCtcC3TZXkvb2Nm2Qg5CjiqPRDTaPTJPIGcYkXyJHkFXXirh/TREqzbgfj/eiO6NZu4WB5jpNrBPlqTTE4l/4bfJGYbV+uDOy/aRKHK8HprCZ5iNoaPWybSF1um9U33uR4c/zQZ2LSVJ2xPnCMioJZ8y8ApZA1ZudM/mBGtK0uQ1w1Q+zBDB1LwalOxC8dOJNEk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
