travis:
  secure:
    BINSTAR_TOKEN: jMJ0WcRiJKdT4ku7VO4igJCsvAipb59O7QSvNwFTUGaPYjgJu+dMDHQvgfavtOBmOXWphhxtBr2yyOoW4U43Yn3lALWhNsc2R1ity2bnjThEwy86P981PwUE+YrH1IDYwyO11ph1NL5XGZuiuqChtQ6R02MeSgm95puqfmUNly43TOf4c4g2bReOyk8zQllpSImtEBMfAKpfYHeqb5pBaVIAzLP6x8RtDU9OeOy5+iGKFI1S2hRzHEOg6KGc6nbKs2vptd3B1ils1FvBUb7EKFLDY/nbOpKBsxTegq/RNV7tHBO0Nvqt92aCrsR0juQTpalb2eRR8fzzwpEctl3n7qrfubD9+MEWKcqjAS1GRqW/Q3Kk9z3jBdNPlNVWbKpZMWRcuokXGC85U32kOV2JlxDMeAekjkjjhlhYJV9ogUoVgc3GZy4A7RGZMktf4AKYpE5s407nYVS6Tp+p5zVGlfS08IhmJJRC8kApS50IDCQ7ORrQY2bkdo+svOMMBwFgX+TV0OhwVgYJAgNGjx7Cm2LzzUhzzeNiEBjG7M2ae9eFZHJkY2NUYsr1/uZd+B+Chn5urGT49ehcnaDyOh00yqmFlgyuojVw/zaYjdHp0OI3mTtmwBibRi8ZDakF9lej/k1Qr3D/ZglsSzdBacVneXv6S3M+GbSseS+1Ze15L4I=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
